name: Build and release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [videohashes, duration, phashcompare]
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.21.9"
          ldflags: "-extldflags=-static -s -w"
          project_path: "./cmd/${{ matrix.project }}"
          asset_name: "${{ matrix.project }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          compress_assets: "OFF"
          overwrite: true
          md5sum: false
          sha256sum: false
